# Export dataset estimates for the interactive explorers at /data/tgov/ and /data/tcs/
#
# Run this whenever the underlying latent-variable models are re-estimated:
#   source("R/export_data_explorers.R")
#
# It reads each project's `theta_summary` object and writes a compact JS file
# that the static explorer pages load with a plain <script> tag. Only the
# aggregate country-year estimates are exported -- never the harmonized
# survey microdata.

# Resolve the site root: run from the project root, or from R/.
site_root <- getwd()
if (!dir.exists(file.path(site_root, "static")) &&
    dir.exists(file.path(site_root, "..", "static"))) {
  site_root <- normalizePath(file.path(site_root, ".."))
}
if (!dir.exists(file.path(site_root, "static"))) {
  stop("Could not find static/. Run this from the website project root.")
}

datasets <- list(
  tgov = list(
    rda   = path.expand("~/Documents/GitHub/TGOV/data/theta_summary.rda"),
    name  = "TGOV",
    label = "Trust in Government",
    unit  = "Trust in government"
  ),
  tcs = list(
    rda   = path.expand("~/Documents/GitHub/dcpo_trust_bureaucracy/data/theta_summary.rda"),
    name  = "TCS",
    label = "Trust in Civil Servants",
    unit  = "Trust in civil servants"
  )
)

num <- function(x) {
  x <- round(as.numeric(x), 4)
  x[is.na(x)] <- NA
  formatC(x, format = "fg", digits = 5, drop0trailing = TRUE)
}

for (key in names(datasets)) {
  d <- datasets[[key]]

  if (!file.exists(d$rda)) {
    warning("Skipping ", d$name, ": not found at ", d$rda)
    next
  }

  env <- new.env()
  load(d$rda, envir = env)
  ts <- get("theta_summary", envir = env)
  ts <- as.data.frame(ts, stringsAsFactors = FALSE)

  keep <- c("country", "year", "mean", "sd", "q10", "q90")
  stopifnot(all(keep %in% names(ts)))
  ts <- ts[, keep]
  ts <- ts[!is.na(ts$mean), ]
  ts <- ts[order(ts$country, ts$year), ]

  countries <- sort(unique(as.character(ts$country)))
  ci <- match(as.character(ts$country), countries) - 1L

  rows <- paste0(
    "[", ci, ",", ts$year, ",",
    num(ts$mean), ",", num(ts$sd), ",",
    num(ts$q10), ",", num(ts$q90), "]"
  )

  out_dir <- file.path(site_root, "static", "data", key)
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

  js <- c(
    "// Generated by R/export_data_explorers.R -- do not edit by hand.",
    sprintf("window.DATASET = {"),
    sprintf("  name: %s,", encodeString(d$name, quote = '"')),
    sprintf("  label: %s,", encodeString(d$label, quote = '"')),
    sprintf("  unit: %s,", encodeString(d$unit, quote = '"')),
    sprintf("  yearMin: %d, yearMax: %d,", min(ts$year), max(ts$year)),
    sprintf("  countries: [%s],",
            paste(encodeString(countries, quote = '"'), collapse = ",")),
    "  // [countryIndex, year, mean, sd, q10, q90]",
    sprintf("  rows: [%s]", paste(rows, collapse = ",")),
    "};"
  )

  writeLines(js, file.path(out_dir, "data.js"))

  # Plain CSV for the download button and for direct reuse.
  utils::write.csv(ts, file.path(out_dir, sprintf("%s_estimates.csv", d$name)),
                   row.names = FALSE)

  message(sprintf("%s: %d rows, %d countries, %d-%d -> %s",
                  d$name, nrow(ts), length(countries),
                  min(ts$year), max(ts$year), out_dir))
}
